[package]
name = "gdk"
license = "MIT"
homepage = "https://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
keywords = ["gdk", "gtk", "gtk-rs", "gnome", "GUI"]
readme = "README.md"
documentation = "https://gtk-rs.org/gtk-rs/stable/docs/gdk/"
version = "0.13.0"
description = "Rust bindings for the GDK 3 library"
repository = "https://github.com/gtk-rs/gtk-rs"
exclude = [
    "gir-files/*",
]
edition = "2018"

[lib]
name = "gdk"

[features]
v3_16 = ["ffi/v3_16"]
v3_18 = ["v3_16", "ffi/v3_18"]
v3_20 = ["v3_18", "ffi/v3_20"]
v3_22 = ["v3_20", "ffi/v3_22"]
v3_24 = ["v3_22", "ffi/v3_24"]
dox = ["ffi/dox", "glib/dox", "gio/dox", "gdk-pixbuf/dox", "cairo-rs/dox", "pango/dox"]

[package.metadata.docs.rs]
features = ["dox"]

[dependencies]
libc = "0.2"
bitflags = "1.0"
ffi = { package = "gdk-sys", path = "sys" }
cairo-rs = { path = "../cairo" }
gdk-pixbuf = { path = "../gdk-pixbuf" }
gio = { path = "../gio" }
glib = { path = "../glib" }
pango = { path = "../pango" }

[dev-dependencies]
gir-format-check = "^0.1"
